export const COMMON_FETCH_CONFIG_INFO_BEGIN = 'COMMON_FETCH_CONFIG_INFO_BEGIN';
export const COMMON_FETCH_CONFIG_INFO_SUCCESS = 'COMMON_FETCH_CONFIG_INFO_SUCCESS';
export const COMMON_FETCH_CONFIG_INFO_FAILURE = 'COMMON_FETCH_CONFIG_INFO_FAILURE';
export const COMMON_FETCH_CONFIG_INFO_DISMISS_ERROR = 'COMMON_FETCH_CONFIG_INFO_DISMISS_ERROR';
